'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Languages, MessageCircle, Search, SlidersHorizontal, X } from 'lucide-react';
import { ApiLoading } from './api-loading';

type Lore={id:string;title:string;text:string;tags:string[];imageUrls:string[];upvotes:number;downvotes:number;commentCount:number};
type Facets={tags:string[];languages:{locale:string;label:string}[]};
const base=()=>process.env.NEXT_PUBLIC_CHARACTER_API_URL?.replace(/\/$/,'')??'';

export function LoreFeed(){
  const[lores,setLores]=useState<Lore[]>([]),[facets,setFacets]=useState<Facets>({tags:[],languages:[]}),[query,setQuery]=useState(''),[debouncedQuery,setDebouncedQuery]=useState(''),[selectedTags,setSelectedTags]=useState<string[]>([]),[language,setLanguage]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{const timer=setTimeout(()=>setDebouncedQuery(query.trim()),300);return()=>clearTimeout(timer)},[query]);
  const requestUrl=useMemo(()=>{const params=new URLSearchParams();if(debouncedQuery)params.set('q',debouncedQuery);selectedTags.forEach(tag=>params.append('tag',tag));if(language)params.set('language',language);return `${base()}/lores${params.size?`?${params}`:''}`},[debouncedQuery,selectedTags,language]);
  useEffect(()=>{if(!base()){setError('Lore archive is not configured.');setLoading(false);return;}const controller=new AbortController();setLoading(true);setError('');fetch(requestUrl,{cache:'no-store',signal:controller.signal}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||'Could not load the lore archive.');return data}).then(data=>{setLores(data.lores??[]);setFacets(data.facets??{tags:[],languages:[]})}).catch(reason=>{if(reason.name!=='AbortError')setError(reason instanceof Error?reason.message:'Could not load the lore archive.')}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[requestUrl]);
  const filtered=Boolean(query||selectedTags.length||language);
  function toggleTag(tag:string){setSelectedTags(items=>items.includes(tag)?items.filter(item=>item!==tag):[...items,tag])}
  function clear(){setQuery('');setSelectedTags([]);setLanguage('')}
  return <section className="lore-browser"><div className="lore-filters"><label className="lore-search"><Search size={18}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search titles, stories, translations…"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={15}/></button>}</label><label className="lore-language-filter"><Languages size={17}/><select value={language} onChange={event=>setLanguage(event.target.value)}><option value="">All languages</option><option value="original">Original edition</option>{facets.languages.map(item=><option value={item.locale} key={item.locale}>{item.label}</option>)}</select></label>{facets.tags.length>0&&<div className="lore-tag-filter"><span><SlidersHorizontal size={15}/>Filter tags</span><div>{facets.tags.map(tag=><button className={selectedTags.includes(tag)?'active':''} onClick={()=>toggleTag(tag)} key={tag}>{tag}</button>)}</div></div>}<div className="lore-results-meta"><span>{loading?'Searching…':`${lores.length} ${lores.length===1?'story':'stories'}`}</span>{filtered&&<button onClick={clear}><X size={14}/>Clear filters</button>}</div></div>{loading?<ApiLoading label="Searching the lore archive…"/>:error?<Empty title="Archive unavailable" description={error}/>:!lores.length?<Empty title="No lore found" description="Try a different search, tag, or language."/>:<div className="lore-feed">{lores.map(lore=><LoreCard lore={lore} key={lore.id}/>)}</div>}</section>
}
function LoreCard({lore}:{lore:Lore}){const excerpt=lore.text.length>320?`${lore.text.slice(0,320).trimEnd()}…`:lore.text;return <article className="lore-card">{lore.imageUrls[0]&&<Link className="lore-cover-link" href={`/lores/${lore.id}/`}><img className="lore-cover" src={lore.imageUrls[0]} alt=""/></Link>}<div className="lore-card-copy"><div className="lore-tags">{lore.tags.map(tag=><span key={tag}>{tag}</span>)}</div><h2><Link href={`/lores/${lore.id}/`}>{lore.title}</Link></h2><p className="lore-excerpt">{excerpt}</p><div className="lore-card-footer"><span>{lore.upvotes-lore.downvotes} score</span><span><MessageCircle size={15}/>{lore.commentCount}</span><Link className="lore-read" href={`/lores/${lore.id}/`}>Read story <ArrowRight size={16}/></Link></div></div></article>}
function Empty({title,description}:{title:string;description:string}){return <div className="lore-empty"><BookOpen size={28}/><h2>{title}</h2><p>{description}</p></div>}
