'use client';
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/exhaustive-deps */
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowBigDown, ArrowBigUp, ArrowLeft, Languages, LogIn, MessageCircle, Send, X } from 'lucide-react';
import { ApiLoading } from './api-loading';
import { useI18n } from './i18n-provider';
import { AppSelect, languageFlag } from './app-select';
import { useAuth } from './auth-provider';
type Translation={locale:string;label:string;title:string;text:string}; type Lore={id:string;title:string;text:string;translations?:Translation[];tags:string[];imageUrls:string[];upvotes:number;downvotes:number;commentCount:number;userVote?:number}; type Comment={id:string;text:string;author:string;authorId?:string;createdAt:string|null}; type Pending={type:'vote'|'comment';value?:1|-1;text?:string;id:string};
const base=()=>process.env.NEXT_PUBLIC_CHARACTER_API_URL?.replace(/\/$/,'')??''; const pendingKey='ambatuapp-lore-pending-action';
export function LoreReader({id}:{id:string}){const{t}=useI18n(),{user,getIdToken,signInWithGoogle}=useAuth();const[lore,setLore]=useState<Lore|null>(null),[locale,setLocale]=useState('original'),[comments,setComments]=useState<Comment[]>([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[commentsOpen,setCommentsOpen]=useState(false),[loginOpen,setLoginOpen]=useState(false);
 const load=async()=>{const token=await getIdToken(),response=await fetch(`${base()}/lores/${encodeURIComponent(id)}`,{cache:'no-store',headers:token?{authorization:`Bearer ${token}`}:{}}),data=await response.json();if(!response.ok)throw new Error(data.error||t('lore.notFound'));setLore(data)};
 useEffect(()=>{void load().catch(reason=>setError(reason instanceof Error?reason.message:t('lore.notFound'))).finally(()=>setLoading(false))},[id,user]);
 const requireLogin=(action:Pending)=>{sessionStorage.setItem(pendingKey,JSON.stringify(action));setLoginOpen(true)};
 async function vote(value:1|-1){if(!user)return requireLogin({type:'vote',value,id});const token=await getIdToken();const response=await fetch(`${base()}/lores/${id}/vote`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({value})}),data=await response.json();if(response.ok&&lore){const prior=lore.userVote??0,next=data.value??0;setLore({...lore,upvotes:lore.upvotes+(next===1?1:0)-(prior===1?1:0),downvotes:lore.downvotes+(next===-1?1:0)-(prior===-1?1:0),userVote:next})}}
 async function openComments(){setCommentsOpen(value=>!value);if(!comments.length){const response=await fetch(`${base()}/lores/${id}/comments`,{cache:'no-store'}),data=await response.json();if(response.ok)setComments(data.comments??[])}}
 async function post(value:string){if(!value.trim())return;if(!user)return requireLogin({type:'comment',text:value,id});const token=await getIdToken(),response=await fetch(`${base()}/lores/${id}/comments`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({text:value})}),data=await response.json();if(response.ok&&lore){setComments(items=>[data,...items]);setLore({...lore,commentCount:lore.commentCount+1});setText('')}}
 useEffect(()=>{if(!user)return;try{const pending=JSON.parse(sessionStorage.getItem(pendingKey)||'null') as Pending|null;if(!pending||pending.id!==id)return;sessionStorage.removeItem(pendingKey);if(pending.type==='vote'&&pending.value)void vote(pending.value);if(pending.type==='comment'&&pending.text){setCommentsOpen(true);void post(pending.text)}}catch{}},[user,id]);
 if(loading)return <div className="page"><ApiLoading label={t('lore.opening')}/></div>; if(error||!lore)return <div className="page"><Link href="/lores/" className="back-link"><ArrowLeft size={17}/>{t('lore.archive')}</Link><div className="lore-empty"><h2>{t('lore.notFound')}</h2><p>{error}</p></div></div>; const translation=lore.translations?.find(item=>item.locale===locale),title=translation?.title??lore.title,body=translation?.text??lore.text;
 return <div className="page lore-reading-page"><Link href="/lores/" className="back-link"><ArrowLeft size={17}/>{t('lore.archive')}</Link><article className="lore-reader"><header><div className="lore-tags">{lore.tags.map(tag=><span key={tag}>{tag}</span>)}</div><h1>{title}</h1><p>{t('lore.minutes',{count:Math.max(1,Math.ceil(body.trim().split(/\s+/).length/220))})}</p>{Boolean(lore.translations?.length)&&<div className="lore-language"><Languages size={17}/><span>{t('lore.readIn')}</span><AppSelect value={locale} onChange={setLocale} ariaLabel={t('lore.readIn')} options={[{value:'original',label:t('lore.original'),icon:'book'},...lore.translations!.map(item=>({value:item.locale,label:item.label,icon:languageFlag(item.locale)}))]}/></div>}</header>{lore.imageUrls?.length > 0 && <div className={`lore-reader-gallery ${lore.imageUrls.length === 1 ? 'single' : ''}`}>{lore.imageUrls.map((url, index) => <img src={url} alt="" key={`${url}-${index}`} loading="lazy" />)}</div>}<div className="lore-prose">{body.split(/\n\s*\n/).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><footer className="lore-reader-actions"><button className={`vote-button up ${lore.userVote===1?'selected':''}`} onClick={()=>void vote(1)}><ArrowBigUp/><span>{t('lore.upvote')}</span><b>{lore.upvotes}</b></button><button className={`vote-button down ${lore.userVote===-1?'selected':''}`} onClick={()=>void vote(-1)}><ArrowBigDown/><span>{t('lore.downvote')}</span><b>{lore.downvotes}</b></button><button className={`comments-button ${commentsOpen?'selected':''}`} onClick={()=>void openComments()}><MessageCircle/><span>{t('lore.comments')}</span><b>{lore.commentCount}</b></button></footer>{commentsOpen&&<section className="comments lore-reader-comments"><form onSubmit={(event:FormEvent)=>{event.preventDefault();void post(text)}}><textarea value={text} onChange={event=>setText(event.target.value)} maxLength={1000} placeholder={t('lore.commentPlaceholder')}/><button aria-label={t('lore.postComment')} disabled={!text.trim()}><Send size={16}/></button></form>{comments.map(item=><p key={item.id}><b>{item.authorId && item.authorId !== user?.id ? <Link href={`/chat/?user=${encodeURIComponent(item.authorId)}&name=${encodeURIComponent(item.author)}`} aria-label={t('chat.messageUser', { name: item.author })}>{item.author}</Link> : item.author}</b>{item.text}</p>)}</section>}</article>{loginOpen&&<div className="auth-popup" role="dialog" aria-modal="true"><div><button className="icon-button" onClick={()=>setLoginOpen(false)} aria-label="Close"><X size={17}/></button><h2>{t('lore.loginTitle')}</h2><p>{t('lore.loginHint')}</p><button className="button dark" onClick={()=>void signInWithGoogle(`${window.location.pathname}${window.location.search}`)}><LogIn size={17}/>{t('profile.googleSignIn')}</button></div></div>}</div>}
