'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useState } from 'react';
import { ArrowBigDown,ArrowBigUp,ArrowLeft,Languages,MessageCircle,Send } from 'lucide-react';
import { ApiLoading } from './api-loading';
import { useI18n } from './i18n-provider';
type Translation={locale:string;label:string;title:string;text:string};
type Lore={id:string;title:string;text:string;translations?:Translation[];tags:string[];imageUrls:string[];upvotes:number;downvotes:number;commentCount:number;userVote?:number};
type Comment={id:string;text:string;createdAt:string|null};
const base=()=>process.env.NEXT_PUBLIC_CHARACTER_API_URL?.replace(/\/$/,'')??'';
function anonymousId(){const key='ambatu-anonymous-id';let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID();localStorage.setItem(key,value)}return value}
const voteKey=(id:string)=>`ambatu-lore-vote:${id}`;
export function LoreReader({id}:{id:string}){
 const{t}=useI18n();
 const[lore,setLore]=useState<Lore|null>(null),[locale,setLocale]=useState('original'),[comments,setComments]=useState<Comment[]>([]),[text,setText]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[commentsOpen,setCommentsOpen]=useState(false),[votePulse,setVotePulse]=useState<'up'|'down'|null>(null);
 useEffect(()=>{const viewer=anonymousId(),savedVote=Number(localStorage.getItem(voteKey(id)))||0;fetch(`${base()}/lores/${encodeURIComponent(id)}?anonymousId=${encodeURIComponent(viewer)}`,{cache:'no-store'}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error||t('lore.notFound'));return{...data,userVote:typeof data.userVote==='number'?data.userVote:savedVote}}).then(setLore).catch(reason=>setError(reason instanceof Error?reason.message:t('lore.notFound'))).finally(()=>setLoading(false))},[id,t]);
 async function vote(value:1|-1){const direction=value===1?'up':'down';setVotePulse(null);requestAnimationFrame(()=>setVotePulse(direction));setTimeout(()=>setVotePulse(null),520);const response=await fetch(`${base()}/lores/${id}/vote`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:anonymousId(),value})}),data=await response.json();if(response.ok&&lore){const prior=lore.userVote??0,next=data.value??0;localStorage.setItem(voteKey(id),String(next));setLore({...lore,upvotes:lore.upvotes+(next===1?1:0)-(prior===1?1:0),downvotes:lore.downvotes+(next===-1?1:0)-(prior===-1?1:0),userVote:next})}}
 async function openComments(){setCommentsOpen(value=>!value);if(!comments.length){const response=await fetch(`${base()}/lores/${id}/comments`,{cache:'no-store'}),data=await response.json();if(response.ok)setComments(data.comments??[])}}
 async function comment(event:FormEvent){event.preventDefault();if(!text.trim()||!lore)return;const response=await fetch(`${base()}/lores/${id}/comments`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:anonymousId(),text})}),data=await response.json();if(response.ok){setComments(items=>[data,...items]);setLore({...lore,commentCount:lore.commentCount+1});setText('')}}
 if(loading)return <div className="page"><ApiLoading label={t('lore.opening')}/></div>;
 if(error||!lore)return <div className="page"><Link href="/lores/" className="back-link"><ArrowLeft size={17}/>{t('lore.archive')}</Link><div className="lore-empty"><h2>{t('lore.notFound')}</h2><p>{error}</p></div></div>;
 const translation=lore.translations?.find(item=>item.locale===locale),title=translation?.title??lore.title,body=translation?.text??lore.text;
 return <div className="page lore-reading-page"><Link href="/lores/" className="back-link"><ArrowLeft size={17}/>{t('lore.archive')}</Link><article className="lore-reader"><header><div className="lore-tags">{lore.tags.map(tag=><span key={tag}>{tag}</span>)}</div><h1>{title}</h1><p>{t('lore.minutes',{count:Math.max(1,Math.ceil(body.trim().split(/\s+/).length/220))})}</p>{Boolean(lore.translations?.length)&&<label className="lore-language"><Languages size={17}/><span>{t('lore.readIn')}</span><select value={locale} onChange={event=>setLocale(event.target.value)}><option value="original">{t('lore.original')}</option>{lore.translations!.map(item=><option value={item.locale} key={item.locale}>{item.label}</option>)}</select></label>}</header>{lore.imageUrls.length>0&&<div className={`lore-reader-gallery ${lore.imageUrls.length===1?'single':''}`}>{lore.imageUrls.map((url,index)=><img src={url} alt={t('lore.imageAlt',{title,number:index+1})} key={url}/>)}</div>}<div className="lore-prose" key={locale}>{body.split(/\n\s*\n/).map((paragraph,index)=><p key={index}>{paragraph}</p>)}</div><footer className="lore-reader-actions"><button className={`vote-button up ${lore.userVote===1?'selected':''} ${votePulse==='up'?'vote-pop':''}`} aria-pressed={lore.userVote===1} onClick={()=>void vote(1)}><ArrowBigUp/><span>{t('lore.upvote')}</span><b>{lore.upvotes}</b></button><button className={`vote-button down ${lore.userVote===-1?'selected':''} ${votePulse==='down'?'vote-pop':''}`} aria-pressed={lore.userVote===-1} onClick={()=>void vote(-1)}><ArrowBigDown/><span>{t('lore.downvote')}</span><b>{lore.downvotes}</b></button><button className={`comments-button ${commentsOpen?'selected':''}`} onClick={()=>void openComments()}><MessageCircle/><span>{t('lore.comments')}</span><b>{lore.commentCount}</b></button></footer>{commentsOpen&&<section className="comments lore-reader-comments"><form onSubmit={event=>void comment(event)}><textarea value={text} onChange={event=>setText(event.target.value)} maxLength={1000} placeholder={t('lore.commentPlaceholder')}/><button aria-label={t('lore.postComment')} disabled={!text.trim()}><Send size={16}/></button></form>{comments.map(item=><p key={item.id}><b>{t('lore.anonymous')}</b>{item.text}</p>)}</section>}</article></div>
}
